#pragma once

#include <cstdint>
#include <deque>
#include <memory>
#include <string>
#include <string_view>
#include <unordered_map>
#include <vector>

// Structure layouts (the Python t4ff's layout.py): every T4 structure's exact MSVC x86 layout, from
// OpenAssetTools' T4_Assets.h (console ones with t4ff's overrides), generated by tools/gen_schema.py.
namespace t4ff
{
enum class TypeKind : uint8_t
{
    Scalar,
    Enum,
    Pointer,
    Array,
    Record,
    Void,
};

// Scalar kinds understood by the zone code (layout.py's SCALARS).
enum class Scalar : uint8_t
{
    None,
    Char,
    SChar,
    UChar,
    Bool,
    Short,
    UShort,
    Int,
    UInt,
    Long,
    ULong,
    LongLong,
    ULongLong,
    Float,
    Double,
};

struct Record;

// A type as a field uses it.
struct TypeRef
{
    TypeKind kind = TypeKind::Void;
    std::string name; // scalar, record or enum name
    uint32_t size = 0;
    uint32_t align = 1;
    const TypeRef *to = nullptr;   // pointer target
    const TypeRef *elem = nullptr; // array element
    uint32_t count = 0;            // array element count
    Scalar scalar = Scalar::None;
    const Record *record = nullptr; // for records, once the layout is linked

    std::string repr() const; // as the Python TypeRef's repr: "GfxImage*", "char[64]", "uint"
};

struct Field
{
    std::string name; // empty for anonymous members
    uint32_t offset = 0;
    const TypeRef *type = nullptr;
    int bit_offset = -1; // inside the storage unit for bitfields
    int bit_width = 0;
};

struct Record
{
    std::string name;
    bool is_union = false;
    uint32_t size = 0;
    uint32_t align = 1;
    std::vector<Field> fields;
    const TypeRef *self = nullptr; // TypeRef("record", name, size, align)

    const Field *field(std::string_view field_name) const;
};

class Layout
{
  public:
    std::string platform;
    std::unordered_map<std::string, int64_t> enums;
    std::unordered_map<std::string, int> enum_sizes;

    const Record *find(std::string_view name) const;
    const Record &record(std::string_view name) const; // throws when missing
    const std::vector<Record *> &all() const
    {
        return order;
    }

    // Types the zone code makes itself (the Python TypeRef("scalar", "char", 1, 1) and so on).
    const TypeRef *scalar(Scalar s) const;
    TypeRef *new_type()
    {
        return &types.emplace_back();
    }

    static std::unique_ptr<Layout> from_json(std::string_view json, std::string platform);

  private:
    std::unordered_map<std::string, std::unique_ptr<Record>> records;
    std::vector<Record *> order;
    std::deque<TypeRef> types;
    const TypeRef *scalars[16] = {};
};

const char *scalar_name(Scalar s);
Scalar scalar_from_name(std::string_view name);
uint32_t scalar_size(Scalar s);
} // namespace t4ff
