"""Development helper: validate console layouts against real Xbox 360 fastfiles.

Every given fastfile is read and written back; when the result is byte identical,
all record types that appear in it are recorded as verified in
t4ff/defs/x360_verified.txt (the converter only converts verified layouts by
default).

    python dev/verify_samples.py path/to/360/*.ff
"""

import os
import sys

sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), ".."))

from t4ff.fastfile import read_fastfile  # noqa: E402
from t4ff.platforms import for_endian  # noqa: E402
from t4ff.zone import Reader, Writer  # noqa: E402

VERIFIED = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "t4ff", "defs", "x360_verified.txt")


def records_of(zone, platform):
    """Record types streamed by the zone, ignoring name only reference assets (all zero data)."""
    from t4ff.zone import asset_name

    names = set()
    stack = [zone.extra_root]
    while stack:
        node = stack.pop()
        origin = node.extra.get("origin")
        if origin and origin[0] == "asset" and asset_name(platform, node).startswith(","):
            continue
        for t, _, _, _ in node.segments:
            while t.kind == "array":
                t = t.elem
            if t.kind == "record":
                names.add(t.name)
        stack.extend(node.children)
    return names


def main(paths):
    verified = set()
    if os.path.exists(VERIFIED) and "--reset" not in paths:
        with open(VERIFIED, "r", encoding="utf-8") as f:
            verified = {line.strip() for line in f if line.strip() and not line.startswith("#")}
    paths = [p for p in paths if p != "--reset"]

    for path in paths:
        endian, _, data = read_fastfile(path)
        if endian != ">":
            print(f"{path}: not a console fastfile, skipped")
            continue
        platform = for_endian(endian)
        zone = Reader(platform, data).load()
        identical = Writer(platform).write(zone) == data
        found = records_of(zone, platform)
        print(f"{path}: {len(zone.assets)} assets, round trip {'identical' if identical else 'DIFFERENT'}, {len(found)} record types")
        if identical:
            verified |= found

    with open(VERIFIED, "w", encoding="utf-8") as f:
        f.write("# Record layouts verified by byte-identical round trips of Xbox 360 fastfiles.\n")
        f.write("# Generated by dev/verify_samples.py\n")
        for name in sorted(verified):
            f.write(name + "\n")
    print(f"{len(verified)} verified record types")


if __name__ == "__main__":
    main(sys.argv[1:])
