param(
    [Parameter(Mandatory = $true)]
    [string]$RepositoryRoot,

    [Parameter(Mandatory = $true)]
    [string]$OutputPath
)

function Write-VersionHeader([string]$Version)
{
    $escapedVersion = $Version.Replace("\", "\\").Replace('"', '\"')
    $content = "// Auto-generated by MSBuild. Do not edit.`r`n#pragma once`r`n`r`n#define GIT_VERSION `"$escapedVersion`"`r`n"

    $directory = [System.IO.Path]::GetDirectoryName($OutputPath)
    [System.IO.Directory]::CreateDirectory($directory) | Out-Null

    if (-not [System.IO.File]::Exists($OutputPath) -or [System.IO.File]::ReadAllText($OutputPath) -ne $content)
    {
        [System.IO.File]::WriteAllText($OutputPath, $content, [System.Text.Encoding]::ASCII)
    }
    Write-Host "GIT_VERSION=$Version"
}

$gitRevision = $null
if (Get-Command git -ErrorAction SilentlyContinue)
{
    $gitRevision = & git -C $RepositoryRoot rev-list --count HEAD 2>$null
}
if (-not $gitRevision -or $LASTEXITCODE -ne 0 -or [string]::IsNullOrWhiteSpace($gitRevision))
{
    if ($env:CODXE_RELEASE_BUILD -eq "1")
    {
        throw "Could not determine the Git version for '$RepositoryRoot'."
    }

    # A source download without Git history (e.g. a ZIP from GitHub) still builds, as a local version.
    Write-Warning "No Git history in '$RepositoryRoot' (a ZIP download?): building as version 'local'."
    Write-VersionHeader "local"
    exit 0
}

$gitHash = & git -C $RepositoryRoot rev-parse --short=8 HEAD 2>$null
if ($LASTEXITCODE -ne 0 -or [string]::IsNullOrWhiteSpace($gitHash))
{
    throw "Could not determine the Git commit for '$RepositoryRoot'."
}

$releaseVersion = "r$($gitRevision.Trim())"

& git -C $RepositoryRoot diff-index --quiet HEAD -- 2>$null
$dirtyExitCode = $LASTEXITCODE
if ($dirtyExitCode -gt 1)
{
    throw "Could not determine the Git working tree state for '$RepositoryRoot'."
}

$exactTag = & git -C $RepositoryRoot describe --tags --exact-match --match $releaseVersion HEAD 2>$null
$isReleaseTag = $LASTEXITCODE -eq 0 -and $exactTag.Trim() -eq $releaseVersion
$isDirty = $dirtyExitCode -eq 1
$isCiRelease = $env:CODXE_RELEASE_BUILD -eq "1"

if ($isCiRelease -and $isDirty)
{
    throw "Refusing to create an official release version from a dirty working tree."
}

if (($isCiRelease -or $isReleaseTag) -and -not $isDirty)
{
    $gitVersion = $releaseVersion
}
else
{
    $gitVersion = "$releaseVersion-g$($gitHash.Trim())"
    if ($isDirty)
    {
        $gitVersion += "-dirty"
    }
}

Write-VersionHeader $gitVersion
