"""Writes native/src/convert/script_templates.inc: the script text the Python t4ff's scripts.py adds
to maps (its functions for options, zombie idles, splitscreen fog and mounted guns), as C++ string
literals, so the native passes add the same bytes.

    python native/tools/gen_templates.py
"""

import os
import sys

NATIVE = os.path.abspath(os.path.join(os.path.dirname(os.path.abspath(__file__)), ".."))
sys.path.insert(0, os.path.dirname(NATIVE))

from t4ff import scripts  # noqa: E402

TEMPLATES = ("_OPTIONS_FUNCTIONS", "_ZOMBIE_IDLE_FUNCTIONS", "_SPLITSCREEN_FOG_FUNCTION", "_MOUNTED_GUN_FUNCTIONS")


def literal(data: bytes) -> str:
    lines = []
    for line in data.split(b"\n"):
        lines.append(line)
    out = []
    for i, line in enumerate(lines):
        text = "".join("\\\\" if c == 0x5C else '\\"' if c == 0x22 else "\\t" if c == 9 else chr(c) if 32 <= c < 127 else f"\\x{c:02x}" for c in line)
        out.append(f'    "{text}' + ('\\n"' if i + 1 < len(lines) else '"'))
    return "\n".join(out)


def main():
    parts = ["// Generated by native/tools/gen_templates.py from t4ff/scripts.py: do not edit.\n"]
    for name in TEMPLATES:
        parts.append(f"static const char {name.lstrip('_')}[] =\n{literal(getattr(scripts, name))};\n")
    path = os.path.join(NATIVE, "src", "convert", "script_templates.inc")
    with open(path, "w", encoding="ascii", newline="\n") as f:
        f.write("\n".join(parts))
    print(path)

    # loadscreen.py's title card font, and menu.py's _ascii of each latin-1 character (map.json)
    from t4ff import loadscreen, menu

    def c_string(text: str) -> str:
        return "".join("\\\\" if ch == "\\" else '\\"' if ch == '"' else ch if 32 <= ord(ch) < 127 else f"\\x{ord(ch):02x}" for ch in text)

    lines = ["// Generated by native/tools/gen_templates.py from t4ff/loadscreen.py and t4ff/menu.py: do not edit.", ""]
    lines += ["// 5x7 glyphs of the title card ('#': set)", "static const struct", "{", "    char c;", "    const char *rows[7];", "} FONT[] = {"]
    for c, rows in loadscreen._FONT.items():
        char = "\\'" if c == "'" else c
        lines.append(f"    {{'{char}', {{" + ", ".join(f'"{r}"' for r in rows) + "}},")
    lines += ["};", "", "// _ascii(chr(c)) of map.json: accents dropped, else '?'", "static const char *const ASCII_OF[256] = {"]
    for c in range(256):
        lines.append(f'    "{c_string(menu._ascii(chr(c)))}", // {c}')
    lines.append("};")
    path = os.path.join(NATIVE, "src", "convert", "loadscreen_tables.inc")
    with open(path, "w", encoding="ascii", newline="\n") as f:
        f.write("\n".join(lines) + "\n")
    print(path)


if __name__ == "__main__":
    main()
